# Generated by Django 4.0.2 on 2022-03-09 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_category_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listing',
            name='title',
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='image_URL',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=100000000),
        ),
    ]
