# Generated by Django 4.0.2 on 2022-03-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_auction_listing_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='title',
            field=models.CharField(default='Title', max_length=60),
        ),
    ]
