# Generated by Django 4.0.2 on 2022-03-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auction_listing_starting_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='auction_listing',
            name='updated',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
