# Generated by Django 4.0.2 on 2022-03-14 01:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_auction_listing_auction_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
