# Generated by Django 4.0.2 on 2022-03-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_bid_auction_bid_current_bid_bid_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='slug',
            field=models.SlugField(default=True, editable=False, verbose_name='Slug'),
        ),
    ]
