# Generated by Django 4.0.2 on 2022-03-21 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auction_listing_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listing',
            name='updated',
        ),
        migrations.AddField(
            model_name='comment',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='auctions.auction_listing'),
        ),
        migrations.AddField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='slug',
            field=models.SlugField(editable=False, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
