# Generated by Django 4.0.2 on 2022-03-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auction_listing_current_bid_validate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='current_bid_validate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='starting_bid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bid',
            name='current_bid',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
