# Generated by Django 4.0.2 on 2022-03-29 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_auction_listing_current_bid_validate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='normal_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listing_normal_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listing_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
