# Generated by Django 4.0.2 on 2022-03-29 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_auction_listing_normal_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, verbose_name='Slug'),
        ),
    ]
