# Generated by Django 4.0.2 on 2022-03-31 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_category_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_listing',
            old_name='normal_user',
            new_name='current_user_bid',
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, verbose_name='Slug'),
        ),
    ]
