# Generated by Django 4.0.2 on 2022-03-31 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_rename_normal_user_auction_listing_current_user_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
