# Generated by Django 4.0.2 on 2022-03-31 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auction_listing_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
